# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cc2e14524e7c70c30871ab64ff0764cb"
application_url = "https://example.com"
embedded = true
name = "my-new-app"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_metaobjects,write_metaobject_definitions,read_customers,write_customers"

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[[webhooks.subscriptions]]
topics = [ "products/update" ]
uri = "/webhooks"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true

scopes = "write_products,write_metaobjects,read_customers,write_customers"